spring.application.name=RankingEngine
server.port=8081

scoring.weights.reaction.liked=0.2
scoring.weights.reaction.disliked=-0.1
scoring.weights.reaction.didntreact=0.0
scoring.weights.recency.week=0.6
scoring.weights.recency.month=0.3
scoring.weights.recency.morethanmonths=0.1