spring.application.name=RankingEngine
server.port=8081

scoring.weights.reaction.liked=0.2
scoring.weights.reaction.disliked=-0.1
scoring.weights.reaction.didntreact=0.0
scoring.weights.recency.week=0.6
scoring.weights.recency.month=0.3
scoring.weights.recency.morethanmonths=0.1

spring.datasource.url=jdbc:postgresql://localhost:5433/RankingEngine
spring.datasource.username=postgres
spring.datasource.password=192837

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest